pipelines:
  - name: "test_pipeline_seed"
    description: "Seeded pipeline"
    enabled: true
    query: "up"
    mode: "forecast_only"
    forecast_schedule: "*/10 * * * *"
    model:
      type: "local"
