# Generated by Django 6.0.1 on 2026-01-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the pipeline', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('query', models.TextField(help_text='PromQL query')),
                ('step', models.CharField(default='1m', help_text='Step size', max_length=50)),
                ('context_window', models.CharField(default='1h', max_length=50)),
                ('prediction_horizon', models.CharField(default='15m', max_length=50)),
                ('mode', models.CharField(choices=[('forecast_only', 'Forecast Only'), ('anomaly_only', 'Anomaly Only'), ('forecast_and_anomaly', 'Forecast and Anomaly')], default='forecast_and_anomaly', max_length=50)),
                ('forecast_schedule', models.CharField(default='*/5 * * * *', help_text='Cron expression', max_length=100)),
                ('anomaly_schedule', models.CharField(default='*/1 * * * *', help_text='Cron expression', max_length=100)),
                ('series_type', models.CharField(choices=[('univariate', 'Univariate'), ('multivariate', 'Multivariate'), ('covariate', 'Covariate')], default='univariate', max_length=50)),
                ('model_config', models.JSONField(default=dict, help_text='Model configuration dictionary')),
                ('training_config', models.JSONField(blank=True, default=dict, help_text='Training configuration', null=True)),
                ('anomaly_config', models.JSONField(default=dict, help_text='Anomaly configuration')),
                ('output_config', models.JSONField(default=dict, help_text='Output configuration')),
                ('covariates', models.JSONField(blank=True, default=list, help_text='List of covariate configs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
