# Generated by Django 5.2.10 on 2026-01-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='anomaly_config',
            field=models.JSONField(blank=True, default=dict, help_text='Anomaly configuration'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='model_config',
            field=models.JSONField(blank=True, default=dict, help_text='Model configuration dictionary'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='output_config',
            field=models.JSONField(blank=True, default=dict, help_text='Output configuration'),
        ),
    ]
