# Generated by Django 5.2.10 on 2026-01-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_alter_pipeline_anomaly_config_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipeline',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pipeline', 'verbose_name_plural': 'Pipelines'},
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='anomaly_config',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='context_window',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='covariates',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='model_config',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='output_config',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='prediction_horizon',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='series_type',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='training_config',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='anomaly_enabled',
            field=models.BooleanField(default=True, help_text='Enable anomaly detection'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='anomaly_threshold',
            field=models.FloatField(default=3.0, help_text='Anomaly sensitivity (higher = less sensitive, e.g., 3.0 for 3-sigma)'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='forecast_context_window',
            field=models.CharField(default='1h', help_text="Historical context for forecasting (e.g., '1h', '2h')", max_length=50),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='forecast_enabled',
            field=models.BooleanField(default=True, help_text='Enable forecast generation'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='forecast_horizon',
            field=models.CharField(default='15m', help_text="How far ahead to forecast (e.g., '15m', '1h')", max_length=50),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='training_enabled',
            field=models.BooleanField(default=False, help_text='Enable periodic model training'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='training_schedule',
            field=models.CharField(default='0 */6 * * *', help_text='Cron expression for training (default: every 6 hours)', max_length=100),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='training_window',
            field=models.CharField(default='7d', help_text="How much historical data to use for training (e.g., '7d', '30d')", max_length=50),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='anomaly_schedule',
            field=models.CharField(default='*/1 * * * *', help_text='Cron expression for anomaly detection (default: every minute)', max_length=100),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='description',
            field=models.TextField(blank=True, help_text='What does this pipeline do?'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Master switch - disable to stop all tasks'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='forecast_schedule',
            field=models.CharField(default='*/5 * * * *', help_text='Cron expression for forecasting (default: every 5 minutes)', max_length=100),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='name',
            field=models.CharField(help_text='Unique name for this pipeline', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='query',
            field=models.TextField(help_text='PromQL query to fetch time series data'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='step',
            field=models.CharField(default='1m', help_text="Query step size (e.g., '1m', '30s')", max_length=50),
        ),
    ]
