
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from openanomaly.pipelines import views

# Create a router and register viewsets
router = DefaultRouter()
router.register(r'pipelines', views.PipelineViewSet, basename='pipeline')

urlpatterns = [
    # CRUD routes for Pipelines (auto-generated by router)
    # GET    /pipelines/          - List all pipelines
    # POST   /pipelines/          - Create pipeline
    # GET    /pipelines/{id}/     - Get pipeline
    # PUT    /pipelines/{id}/     - Update pipeline (full)
    # PATCH  /pipelines/{id}/     - Update pipeline (partial)
    # DELETE /pipelines/{id}/     - Delete pipeline
    #
    # Custom actions:
    # POST   /pipelines/{id}/trigger_forecast/  - Trigger forecast
    # POST   /pipelines/{id}/trigger_anomaly/   - Trigger anomaly
    # POST   /pipelines/{id}/trigger_training/  - Trigger training
    path('', include(router.urls)),
    
    # Stateless execution endpoints
    path('execute/inference', views.ExecuteInferenceView.as_view(), name='execute_inference'),
    path('execute/train', views.ExecuteTrainingView.as_view(), name='execute_training'),
]
